# Generated by Django 6.0.7 on 2026-07-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
