# Generated by Django 6.0.7 on 2026-07-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='sent',
        ),
        migrations.AddField(
            model_name='reminder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='task_id',
            field=models.CharField(null=True),
        ),
    ]
