# Generated by Django 6.0.7 on 2026-07-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_remove_reminder_sent_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='task_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
